export const actionTypes = {
    FETCH_MODE_CHANGED: "FETCH_MODE_CHANGED",
    FETCH_MOVIES: "FETCH_MOVIES",
    FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
    FETCH_MOVIES_FAILED: "FETCH_MOVIES_FAILED",
    FETCH_WIKIPEDIA_EXTRACT: "FETCH_WIKIPEDIA_EXTRACT",
    FETCH_WIKIPEDIA_EXTRACT_SUCCESS: "FETCH_WIKIPEDIA_EXTRACT_SUCCESS",
    FETCH_WIKIPEDIA_EXTRACT_FAILED: "FETCH_WIKIPEDIA_EXTRACT_FAILED"
};
